//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneGen {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtPhNum;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator phNumValidation;
		
		protected System.Web.UI.WebControls.Literal ltNumberOutput;
		
		protected System.Web.UI.WebControls.GridView grdPhGrid;
	}
}
